server:
  port: 8080

spring:
  application:
    name: cloud-order-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/dp2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样取值介于 0到1之间，1则表示全部收集 一般值为0.5
eureka:
  client:
    # 注册进server
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
