server:
  port: 8080
spring:
  application:
    name: cloud-consumer-payment
  # consul注册中心
  cloud:
    consul:
      host: hymbb.cn
      port: 8500
      discovery:
        #hostname: hymbb.cn
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true

