spring:
  application:
    name: cloud-sentinel-service
  cloud:
#    nacos:
#      discovery:
#        server-addr: hymbb.cn:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yaml
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
#        port: 8719 # 默认8719
#        clientIp: 106.52.106.112
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-flow
            groupId: DEFAULT_GROUP
            namespace: sentinelRule
            data-type: json
            # flow：流控  degrade：降级 param-flow：热点 system：系统 authority:授权
            rule-type: flow
        ds2:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-degrade
            groupId: DEFAULT_GROUP
            namespace: sentinelRule
            data-type: json
            # flow：流控  degrade：降级 param-flow：热点 system：系统 authority:授权
            rule-type: degrade
        ds3:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-paramFlow
            groupId: DEFAULT_GROUP
            namespace: sentinelRule
            data-type: json
            # flow：流控  degrade：降级 param-flow：热点 system：系统 authority:授权
            rule-type: param-flow
#        ds4:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            dataId: ${spring.application.name}-system
#            groupId: DEFAULT_GROUP
#            namespace: sentinelRule
#            data-type: json
#            # flow：流控  degrade：降级 param-flow：热点 system：系统 authority:授权
#            rule-type: system
#        ds5:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            dataId: ${spring.application.name}-authority
#            groupId: DEFAULT_GROUP
#            namespace: sentinelRule
#            data-type: json
#            # flow：流控  degrade：降级 param-flow：热点 system：系统 authority:授权
#            rule-type: authority
    # rocketmq
#    stream:
#      rocketmq:
#        binder:
#          name-server: 192.168.50.2:9876
##        bindings:
##          output1:
##            producer:
##              group: test # 生产者分组
##          input1:
###             RocketMQ Consumer 配置项，对应 RocketMQConsumerProperties 类
##            consumer:
###              tags: tagStr
##              enabled: true # 是否开启消费，默认为 true
###              broadcasting: false # 是否使用广播消费，默认为 false 使用集群消费，如果要使用广播消费值设成true。
##          input1:
##            consumer:
##              enabled: true
##              tags: tagStr || tagstr
#      bindings:
#        output1:
#          destination: OUTPUT-01 # 目的地。这里使用 RocketMQ Topic
#          content-type: application/json # 内容格式。这里使用 JSON
#        input1:
#          destination: OUTPUT-01 # 目的地。这里使用 RocketMQ Topic
#          content-type: application/json # 内容格式。这里使用 JSON
#          group: test-group1 # 消费者分组,命名规则：组名+topic名
#        input2:
#          destination: OUTPUT-01 # 目的地。这里使用 RocketMQ Topic
#          content-type: application/json # 内容格式。这里使用 JSON
#          group: test-group2 # 消费者分组,命名规则：组名+topic名

management:
  endpoints:
    web:
      exposure:
        include: "*"

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true

rocketmq:
  name-server: 192.168.50.2
